from setuptools import setup, find_packages

setup(
    name="cfm-tts-pytorch",
    version="0.1.0",
    description="A PyTorch implementation of Continuous Flow Matching for Text-to-Speech synthesis",
    author="Phu Vinh Nguyen",
    author_email="phuvinhnguyen@gmail.com",
    url="https://github.com/phuvinhnguyen/cfm-tts-pytorch",
    packages=find_packages(),
    install_requires=[
        'accelerate>=0.33.0',
        'adam-atan2-pytorch>=0.1.12',
        'beartype',
        'einops>=0.8.0',
        'einx>=0.3.0',
        'ema-pytorch>=0.5.2',
        'hl-gauss-pytorch>=0.1.7',
        'hyper-connections>=0.0.10',
        'g2p-en',
        'jaxtyping',
        'loguru',
        'pydantic<2',
        'tensorboard',
        'torch>=2.0',
        'torchdiffeq',
        'torchaudio>=2.3.1',
        'tqdm>=4.65.0',
        'vocos',
        'x-transformers>=1.42.23',
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
